import java.io.File;
import java.sql.*;
import java.util.*;

public class GuestbookDB {

    private static final GuestbookDB _shared = new GuestbookDB();

    public static GuestbookDB shared() { return _shared; }

    private final Connection conn;

    private GuestbookDB() {
        try {
            new File("/data/guestbook").mkdirs();
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            conn = DriverManager.getConnection(
                "jdbc:hsqldb:file:/data/guestbook/gb;hsqldb.write_delay=false",
                "SA", ""
            );
            initSchema();
        } catch (Exception e) {
            throw new RuntimeException("GuestbookDB init failed", e);
        }
    }

    private void initSchema() throws SQLException {
        Statement st = conn.createStatement();
        st.execute(
            "CREATE TABLE IF NOT EXISTS ENTRIES (" +
            "  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "  posted_at  TIMESTAMP DEFAULT NOW()," +
            "  name       VARCHAR(100)  NOT NULL," +
            "  email      VARCHAR(200)," +
            "  location   VARCHAR(200)," +
            "  message    LONGVARCHAR   NOT NULL" +
            ")"
        );
        conn.commit();
        st.close();
    }

    public synchronized List<GuestbookEntry> allEntries() {
        List<GuestbookEntry> list = new ArrayList<>();
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(
                "SELECT name, email, location, message, posted_at " +
                "FROM ENTRIES ORDER BY id DESC"
            );
            while (rs.next()) {
                list.add(new GuestbookEntry(
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("location"),
                    rs.getString("message"),
                    rs.getTimestamp("posted_at")
                ));
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public synchronized void addEntry(String name, String email,
                                      String location, String message) {
        try {
            PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO ENTRIES (name, email, location, message) VALUES (?,?,?,?)"
            );
            ps.setString(1, name);
            ps.setString(2, (email    == null || email.trim().isEmpty())    ? null : email.trim());
            ps.setString(3, (location == null || location.trim().isEmpty()) ? null : location.trim());
            ps.setString(4, message);
            ps.executeUpdate();
            conn.commit();
            ps.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public synchronized int entryCount() {
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM ENTRIES");
            rs.next();
            int n = rs.getInt(1);
            rs.close();
            st.close();
            return n;
        } catch (SQLException e) {
            return 0;
        }
    }
}
